<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.72" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Hangfire" Version="1.8.23" />
	  <PackageReference Include="MediatR" Version="14.1.0" />
	  <FrameworkReference Include="Microsoft.AspNetCore.App" />
	  <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\SharedKernel\SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Abstractions\ExternalServices\" />
    <Folder Include="Email\" />
  </ItemGroup>
	
 <ItemGroup>
		<Reference Include="EmailSenderUtility">
			<HintPath>..\Application\EmailSenderUtility.dll</HintPath>
		</Reference>
 </ItemGroup>

</Project>
