# fly.toml app configuration file generated for aibugdetection-keycloak on 2026-04-23T12:16:18+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aibugdetection-keycloak'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  ASPNETCORE_ENVIRONMENT = 'Production'
  ASPNETCORE_URLS = 'http://+:8080'
  DOTNET_RUNNING_IN_CONTAINER = 'true'
  DOTNET_VERSION = '9.0'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
