app = "aibugdetection-keycloak"
primary_region = "iad"

[build]
  image = "quay.io/keycloak/keycloak:24.0"

[env]
  KC_HTTP_ENABLED = "true"
  KC_HOSTNAME_STRICT = "false"
  KC_PROXY = "edge"
  KC_DB = "postgres"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1